source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DZFileUtils_Example', :exclusive => true do
  pod 'DZFileUtils', :path => '../'
end

target 'DZFileUtils_Tests', :exclusive => true do
  pod 'DZFileUtils', :path => '../'

  pod 'FBSnapshotTestCase'
end
